soc_dashboard_index:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

soc_dashboard_news:
    path:     /dashboard/news
    defaults: { _controller: AppBundle:Default:news }

soc_lineup_index:
    path:     /lineup
    defaults: { _controller: AppBundle:Default:lineup }

soc_lineup_print:
    path:     /lineup/{matchday}/print.{_format}
    defaults: { _controller: AppBundle:Default:lineupPrint }
    requirements:
        _format: html|pdf

soc_team_index:
    path:     /team
    defaults: { _controller: AppBundle:Default:team }

soc_standings_index:
    path:     /standings
    defaults: { _controller: AppBundle:Default:index }

soc_matchday_index:
    path:     /matchday
    defaults: { _controller: AppBundle:Default:index }

soc_player:
    resource: "@AppBundle/Resources/config/routing/player.yml"
    prefix:   /player





